name: Update SDK
on:
  ## External event triggered by Repository
  repository_dispatch:
    types: [openapi-spec-change]
  ## Manual request that can be used for testing and retriggering failed updates
  workflow_dispatch:
    inputs:
      url: 
        description: 'Type of SDK event to handle'     
        required: true
        type: choice
        options:
        - "https://raw.githubusercontent.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/main/openapi/kas-fleet-manager.yaml"
        - "https://raw.githubusercontent.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/main/openapi/connector_mgmt.yaml"
        - "https://raw.githubusercontent.com/bf2fc6cc711aee1a0c2a/srs-fleet-manager/main/core/src/main/resources/srs-fleet-manager.json"

jobs:
  generate_client:
    env:
      APP_SERVICES_TOKEN: ${{ secrets.APP_SERVICES_TOKEN }}
      BF2_TOKEN: ${{ secrets.BF2_TOKEN }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
      - uses: actions/checkout@v3
      - name: Install jq
        run: sudo apt-get install jq
      - name: Fetch OpenAPI doc
        if: github.event.inputs.url != ''
        run: ./scripts/fetch_api.sh ${{ github.event.inputs.url }}
      - name: Fetch OpenAPI doc
        if: github.event.client_payload.download_url != ''
        run: ./scripts/fetch_api.sh ${{ github.event.client_payload.download_url }}